<?php

declare(strict_types=1);

/**
 * @file
 * Provides a test_entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function test_module_theme(): array {
  return [
    'test_module_test_entity' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for test_entity templates.
 *
 * Default template: test-module-test-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the test_entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_test_module_test_entity(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function test_module_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish test_entities.
      $storage = \Drupal::entityTypeManager()->getStorage('test_module_test_entity');
      $test_module_test_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($test_module_test_entity_ids) as $test_module_test_entity) {
        $test_module_test_entity->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize test_entities.
      $storage = \Drupal::entityTypeManager()->getStorage('test_module_test_entity');
      $test_module_test_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($test_module_test_entity_ids) as $test_module_test_entity) {
        $test_module_test_entity->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function test_module_user_predelete(UserInterface $account): void {
  // Delete test_entities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('test_module_test_entity');
  $test_module_test_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($test_module_test_entity_ids)
  );
}
